### ISSUE TITLE
Viewing a single post I get a 500 error - Author Template

### ISSUE THREAD

**Issue by jasontucker** [janboddez/indieblocks#108]
When viewing a single post I'm getting this error:

thrown in /sites/jasontucker.blog/files/wp-includes/author-template.php on line 362

[18-Jun-2023 17:14:15 UTC] PHP Warning: Attempt to read property "post_type" on null in /sites/jasontucker.blog/files/wp-content/plugins/indieblocks-main/includes/functions.php on line 123

[18-Jun-2023 17:14:35 UTC] PHP Warning: Attempt to read property "post_type" on null in /sites/jasontucker.blog/files/wp-content/plugins/indieblocks-main/includes/functions.php on line 123

[18-Jun-2023 17:14:38 UTC] PHP Warning: Attempt to read property "post_type" on null in /sites/jasontucker.blog/files/wp-content/plugins/indieblocks-main/includes/functions.php on line 123

[18-Jun-2023 17:14:40 UTC] PHP Warning: Attempt to read property "post_type" on null in /sites/jasontucker.blog/files/wp-content/plugins/indieblocks-main/includes/functions.php on line 123

[18-Jun-2023 17:14:41 UTC] PHP Warning: Attempt to read property "post_type" on null in /sites/jasontucker.blog/files/wp-content/plugins/indieblocks-main/includes/functions.php on line 123

[18-Jun-2023 17:14:43 UTC] PHP Warning: Attempt to read property "post_type" on null in /sites/jasontucker.blog/files/wp-content/plugins/indieblocks-main/includes/functions.php on line 123

[18-Jun-2023 17:14:47 UTC] PHP Warning: Attempt to read property "post_type" on null in /sites/jasontucker.blog/files/wp-content/plugins/indieblocks-main/includes/functions.php on line 123

[18-Jun-2023 17:14:51 UTC] PHP Warning: Attempt to read property "post_type" on null in /sites/jasontucker.blog/files/wp-content/plugins/indieblocks-main/includes/functions.php on line 123

[18-Jun-2023 17:15:16 UTC] PHP Warning: Attempt to read property "post_type" on null in /sites/jasontucker.blog/files/wp-content/plugins/indieblocks-main/includes/functions.php on line 123

[18-Jun-2023 17:15:16 UTC] PHP Warning: Attempt to read property "post_type" on null in /sites/jasontucker.blog/files/wp-content/plugins/indieblocks-main/includes/functions.php on line 123

[18-Jun-2023 17:15:20 UTC] PHP Warning: Attempt to read property "post_type" on null in /sites/jasontucker.blog/files/wp-content/plugins/indieblocks-main/includes/functions.php on line 123

[18-Jun-2023 17:15:26 UTC] PHP Warning: Attempt to read property "post_type" on null in /sites/jasontucker.blog/files/wp-content/plugins/indieblocks-main/includes/functions.php on line 123

[18-Jun-2023 17:15:28 UTC] PHP Warning: Attempt to read property "post_type" on null in /sites/jasontucker.blog/files/wp-content/plugins/indieblocks-main/includes/functions.php on line 123

[18-Jun-2023 17:15:29 UTC] PHP Fatal error: Uncaught ArgumentCountError: Too few arguments to function get_author_posts_url(), 0 passed in /sites/jasontucker.blog/files/wp-content/plugins/indieblocks-main/includes/class-theme-mf2.php on line 281 and at least 1 expected in /sites/jasontucker.blog/files/wp-includes/author-template.php:362

Stack trace:

#0 /sites/jasontucker.blog/files/wp-content/plugins/indieblocks-main/includes/class-theme-mf2.php(281): get_author_posts_url()

#1 /sites/jasontucker.blog/files/wp-includes/class-wp-block.php(258): IndieBlocks\Theme_Mf2::render_block_core_post_author()

#2 /sites/jasontucker.blog/files/wp-includes/class-wp-block.php(244): WP_Block->render()

#3 /sites/jasontucker.blog/files/wp-includes/class-wp-block.php(244): WP_Block->render()

#4 /sites/jasontucker.blog/files/wp-includes/class-wp-block.php(244): WP_Block->render()

#5 /sites/jasontucker.blog/files/wp-includes/blocks.php(1072): WP_Block->render()

#6 /sites/jasontucker.blog/files/wp-includes/blocks.php(1110): render_block()

#7 /sites/jasontucker.blog/files/wp-includes/block-template.php(242): do_blocks()

#8 /sites/jasontucker.blog/files/wp-includes/template-canvas.php(12): get_the_block_template_html()

#9 /sites/jasontucker.blog/files/wp-includes/template-loader.php(106): include('...')

#10 /sites/jasontucker.blog/files/wp-blog-header.php(19): require_once('...')

#11 /sites/jasontucker.blog/files/index.php(17): require('...')

#12 {main}

thrown in /sites/jasontucker.blog/files/wp-includes/author-template.php on line 362

[18-Jun-2023 17:15:30 UTC] PHP Warning: Attempt to read property "post_type" on null in /sites/jasontucker.blog/files/wp-content/plugins/indieblocks-main/includes/functions.php on line 123

**Comment by jasontucker** [comment]
My settings:

![CleanShot 2023-06-18 at 10 33 48@2x](https://github.com/janboddez/indieblocks/assets/108426/8a34963a-1d3f-404f-89bd-7262efaef2f6)

**Comment by janboddez** [comment]
Oopsie ... It was a change I made in the author block; should be fixed now. Previously, if you hadn't set a website in your user profile, it would return the homepage. Now it instead returns your author archive (of which the address can be filtered, so you could still return something else). Except I _had_ such a filter in place and would thus not see the issue ...

**Comment by janboddez** [comment]
> Attempt to read property "post_type" on null

This (unrelated) issue should also be fixed.

I added a check so that only singular posts, notes, etc. would be able to receive webmentions (and not archive pages and so on). Also, it now respects the comment term in WP's discussion settings (i.e., if comments close after 14 days, so do webmentions and no webmention endpoint will be printed in the `head` of that post's HTML).

Previously, webmentions would stay open always.

Except, my check contained an error ...
